pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  #computers:
    #type: diagnostic_aggregator/AnalyzerGroup
    #path: Computers
    #analyzers:
      #b1:
        #type: diagnostic_aggregator/GenericAnalyzer
        #path: b1
        #contains: ['RT CPU Info', 'RT CPU Usage', 'RT HD Usage', 'RT Memory Usage']
#  network:
#    type: diagnostic_aggregator/AnalyzerGroup
#    path: Network
#    analyzers:
#      wifi:
#        type: diagnostic_aggregator/GenericAnalyzer
#        path: wifi
#        num_items: 1
#        expected: ['Wifi Status (ddwrt)']

  io:
    type: diagnostic_aggregator/AnalyzerGroup
    path: IO
    analyzers:
      joystick:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Joystick
        contains: 'joy'
      #light:
        #type: diagnostic_aggregator/GenericAnalyzer
        #path: Light
        #contains: 'light'

  sensors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Sensors
    analyzers:
      laser_right:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Right
        contains: 'laser_right'
      laser_left:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Left
        contains: 'laser_left'
      laser_back:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Rear
        contains: 'laser_back'

  motors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Actuators
    analyzers:
      base:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Base
        remove_prefix: base_driver
        contains: ['caster', 'chain']

  safety:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Safety
    contains: 'Safety'

  controllers:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Controllers
    remove_prefix: base_driver
    contains: 'RoboTrainer Controller'
    discard_stale: true
    
  robotrainer_hw:
    type: diagnostic_aggregator/GenericAnalyzer
    path: RoboTrainerHW
    contains: 'Battery'
    discard_stale: true
