# robotrainer 2
##########
# common params
run_factor: 5.0
apply_ramp: false
joy_num_buttons: 11 #12
joy_num_axes: 4 #6
joy_num_modes: 1
mode_switch_button: 8

#enable_light: false
#light_action_name: /light_base/set_light
#enable_sound: false
#sound_action_name: /sound/say

# axes
axis_vx: 1
axis_vy: 0
axis_vz: 5
axis_roll: 4
axis_pitch: 3
axis_yaw: 2

# buttons
deadman_button: 5
safety_button: 4
init_button: 9

#mode1: Base
run_button: 7

components: {
  base: {
    twist_topic_name: '/base/twist_mux/command_teleop_joy',
    twist_safety_topic_name: '/base/twist_mux/command_teleop_joy',
    twist_max_velocity: [0.4, 0.3, 0.2],
    twist_max_acc: [0.2, 0.2, 0.2]
  }
}
